<?php foreach ($this->listePj as $pj) : ?>
<tr id="<?php echo $pj['ID_PIECEJOINTE']?>" class="pjID">   
    <?php /* Lien de la pièce jointe */ ?>
    <td>
        <!--<a modified by george (pas d'extension de fichier
            class="file <?php echo substr(strtolower($pj['EXTENSION_PIECEJOINTE']), 1, 3) ?>"
            href='<?php echo $this->url(array('controller' => 'piece-jointe', 'action' => 'get', 'id' => $this->id, 'idpj' => $pj['ID_PIECEJOINTE'], 'type' => $this->type)) ?>' <?php if ($pj['DESCRIPTION_PIECEJOINTE']): ?> title="<?php echo $pj['DESCRIPTION_PIECEJOINTE'] ?>" <?php endif ?> target='_blank' ><?php echo $pj['NOM_PIECEJOINTE'].$pj['EXTENSION_PIECEJOINTE'] ?></a> -->
        <a 
            class="file <?php echo substr(strtolower($pj['EXTENSION_PIECEJOINTE']), 1, 3) ?>"
            href='<?php echo $this->url(array('controller' => 'piece-jointe', 'action' => 'get', 'id' => $this->id, 'idpj' => $pj['ID_PIECEJOINTE'], 'type' => $this->type)) ?>' <?php if ($pj['DESCRIPTION_PIECEJOINTE']): ?> title="<?php echo $pj['DESCRIPTION_PIECEJOINTE'] ?>" <?php endif ?> target='_blank' ><?php echo $pj['NOM_PIECEJOINTE'] ?></a>
    </td>
    
    <?php /* Description */ ?>
    <td><?php echo nl2br(str_replace("<br />", "" ,$pj['DESCRIPTION_PIECEJOINTE'])) ?></td>
    
    <?php /* date de création*/ ?>
    <td>
        <?php
            $date = new Zend_Date($pj['DATE_PIECEJOINTE'], Zend_Date::DATES);
            echo $date->get( Zend_Date::DAY."/".Zend_Date::MONTH."/".Zend_Date::YEAR );
        ?>
    </td>
    <?php /* Action*/ ?>
    <td style='text-align: center; width: 350px;'>
        <script type="text/javascript">
            $(document).ready(function(){
                $('#formUpdate_<?php echo $pj['ID_PIECEJOINTE'] ?>').hide();
                $('#update_<?php echo $pj['ID_PIECEJOINTE'] ?>').click(function(){
                    $('#formUpdate_<?php echo $pj['ID_PIECEJOINTE'] ?>').toggle(600);
                });
                $('form').submit(function(){
                    $('#formUpdate_<?php echo $pj['ID_PIECEJOINTE'] ?>').hide();
                });
            });
        </script>
        <a name='update_<?php echo $pj['ID_PIECEJOINTE'] ?>' id='update_<?php echo $pj['ID_PIECEJOINTE'] ?>' href='#' title='Mettre à jour'><i class="icon-refresh"></i></a>
        <form method='post' id='formUpdate_<?php echo $pj['ID_PIECEJOINTE'] ?>' name='formUpdate_<?php echo $pj['ID_PIECEJOINTE'] ?>' enctype='multipart/form-data' action='/piece-jointe/update' target='hiddeniframe' >
            Fichier
            <input type='file' name='majfichier' id='majfichier' size='30' />
            <input type='hidden' name='idpj' id='identifiant' value='<?php echo $pj['ID_PIECEJOINTE'].$pj['EXTENSION_PIECEJOINTE'] ?>' /><br />
            <input type='submit' value='Mettre à jour' />
        </form>
    </td>
    <td>
        <?php if($this->verrou != 1): ?>
            <a class='delete' href='/piece-jointe/delete?id_pj=<?php echo $pj["ID_PIECEJOINTE"] ?>&type=<?php echo $this->type ?>&id=<?php echo $this->id ?>'>
                <i class="icon-trash"></i>
            </a>
        <?php endif ?>
    </td>
</tr>
<?php endforeach ?>