<!doctype html>
<title>Site Maintenance</title>
<style>
  body { text-align: center; padding: 50px; }
  h1 { font-size: 30px; }
  body { font: 20px Helvetica, sans-serif; color: #333; }
  article { display: block; text-align: left; width: 650px; margin: 0 auto; }
  a { color: #dc8100; text-decoration: none; }
  a:hover { color: #333; text-decoration: none; }
</style>

<article>
    <h1>PREVARISC est temporairement indisponible</h1>
    <div>
        <p>Pour des raisons de maintenance, prevarisc est temporairement indisponible. Veuillez nous excuser pour la gêne occasionnée.</p>
        <p>&mdash; GSIC</p>
    </div>
</article>