<h1>
    Aie !
    <small>Une erreur '<?php echo $this->message ?>' est survenue ...</small>
</h1>

<p class="lead">
    <strong>Pas de panique !</strong> 
    Envoyez cette page au <a href="mailto:assistance_sic@sdis91.fr">GSIC</a> ('Ctrl a' puis copier et coller dans un message avec une explication de ce que vous faisiez) qui essayera de traiter le problème.
</p>

<?php if (!$this->showException): ?>
<!--
<?php endif ?>
<div class="well">
    <h3>Exception information:</h3>
    <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
    </p>

    <h3>Stack trace:</h3>
    <pre><?php echo $this->exception->getTraceAsString() ?>
    </pre>

    <h3>Request Parameters:</h3>
    <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
    </pre>
</div>
<?php if (!$this->showException): ?>
-->
<?php endif ?>