
-- ajout de statut (modification annulée) => demande de Karine le 20/05/2021
--INSERT INTO `statut` (`ID_STATUT`, `LIBELLE_STATUT`) VALUES (NULL, 'En exploitation');
-- INSERT INTO `statut` (`ID_STATUT`, `LIBELLE_STATUT`) VALUES (NULL, "Cessation d'activité");

-- ajout de genre
INSERT INTO `genre` (`ID_GENRE`, `LIBELLE_GENRE`) VALUES (NULL, 'Linéaire - Fluvial'); 13
INSERT INTO `genre` (`ID_GENRE`, `LIBELLE_GENRE`) VALUES (NULL, 'Linéaire - Transport guidé'); 14
INSERT INTO `genre` (`ID_GENRE`, `LIBELLE_GENRE`) VALUES (NULL, 'Linéaire - Routier'); 15
INSERT INTO `genre` (`ID_GENRE`, `LIBELLE_GENRE`) VALUES (NULL, 'Plans'); 16
INSERT INTO `genre` (`ID_GENRE`, `LIBELLE_GENRE`) VALUES (NULL, 'Linéaire - Fluides') 17

-- le cas de gestion des dossiers :  

--ajout de dossiertype

INSERT INTO `dossiertype` (`ID_DOSSIERTYPE`, `LIBELLE_DOSSIERTYPE`) VALUES ('9', 'Avis Prévision'); 

-- pour alimenter la liste des dossier 

--- ajout de dossier nature

INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (NULL, "Dossier de Demande d'Autorisation Environnementale", '1', 1);

INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (NULL, "Demande d'enregistrement", '1', 1);

INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (NULL, "Plan d'intervention", '1', 1);

INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (NULL, "Plan d'urbanisme", '1', 1);

INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (NULL, "Porter à connaissance", '1', 1);

INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (NULL, 'Autre', '1', 1);




-- pour le type "Avis Prévision" : même chose que le type "Etude" :

INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, 'Permis de construire (PC)', 9, 2);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, 'Autorisation de travaux (AT)', 9, 1);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, 'Demande de Dérogation', 9, 5);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, 'Cahier des charges fonctionnel du SSI', 9, 13);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, 'Cahier des charges', 9, 15);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, 'PC / PCM / AT communs', 9, 4);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, 'Levée de prescriptions', 9, 12);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, 'Documents divers', 9, 23);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, 'Changement de DUS (Directeur unique de sécurité)', 9, 10);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, "Demande d'implantation CTS < 6mois", 9, 21);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, "Demande d'implantation CTS > 6mois", 9, 22);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, "Permis d'aménager (PA)", 9, 7);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, "Utilisation exceptionnelle de locaux", 9, 9);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, "Diagnostique sécurité", 9, 16);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, 'Echéancier de travaux', 9, 11);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, "Certificats d'urbanisme (CU)", 9, 8);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, "Demande d'organisation de manifestation temporaire", 9, 17);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, "Modification Classement / Effectif", 9, 18);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, 'Permis de construire modificatif (PCM)', 9, 3);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, 'Demande préalable (DP)', 9, 6);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, 'Certificat de conformité', 9, 14);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, 'Homologation CTS', 9, 19);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (null, 'Retrait de conformité CTS', 9, 20); 
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (NULL, "Dossier de Demande d'Autorisation Environnementale", 9, 1);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (NULL, "Demande d'enregistrement", 9, 1);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (NULL, "Plan d'intervention", 9, 1);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (NULL, "Plan d'urbanisme", 9, 1);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (NULL, "Porter à connaissance", 9, 1);
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (NULL, 'Autre', 9, 1);

-- ajout de service instructeur (à voir avec Karine) : page 29 ==> 
-- la table en question est "`groupement`" : avec ID_GROUPEMENTTYPE = 10 (service instructeur) : il me faut le ID_UTILISATEURINFORMATIONS : 
-- j'ai trouvé (table : utilisteurinformations) pour Evry : ID_UTILISATEURINFORMATIONS = 54 (PETEL YANN), pour essonne (52 : TRON Georges)
-- ?????????????????????? 
-- pour tester avec le profil de Karine (ID_UTILISATEURINFORMATIONS = 10)
-- modification de "DRIEE" par "DRIEAT" demandé par Karine le 21/05/2021
INSERT INTO `groupement` (`ID_GROUPEMENT`, `LIBELLE_GROUPEMENT`, `ID_UTILISATEURINFORMATIONS`, `ID_GROUPEMENTTYPE`) VALUES (NULL, 'DRIEAT', '10', '10');
INSERT INTO `groupement` (`ID_GROUPEMENT`, `LIBELLE_GROUPEMENT`, `ID_UTILISATEURINFORMATIONS`, `ID_GROUPEMENTTYPE`) VALUES (NULL, 'BDPC', '10', '10');
INSERT INTO `groupement` (`ID_GROUPEMENT`, `LIBELLE_GROUPEMENT`, `ID_UTILISATEURINFORMATIONS`, `ID_GROUPEMENTTYPE`) VALUES (NULL, 'Commune', '10', '10')

-- demandé par Karine le 28/10/2020
INSERT INTO `groupement` (`ID_GROUPEMENT`, `LIBELLE_GROUPEMENT`, `ID_UTILISATEURINFORMATIONS`, `ID_GROUPEMENTTYPE`) VALUES (NULL, 'DIRECCTE', '10', '10');


-- ajout de la nature "compte-rendu" au type "Groupe de visite" 
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (NULL, 'Compte-rendu', '3', '7');

-- ajout de la nature "Information" au type "Courrier /couriel" 
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (NULL, 'Information', '5', '13');

-- ajout de la nature "Préfectoral", "Municipal", "Autre"
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (NULL, 'Préfectoral', '7', '6');
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (NULL, 'Municipal', '7', '7');
INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (NULL, 'Autre', '7', '8');

-- ajout de la nature "Etablissements Prévision" au type "Intervention" 

INSERT INTO `dossiernatureliste` (`ID_DOSSIERNATURE`, `LIBELLE_DOSSIERNATURE`, `ID_DOSSIERTYPE`, `ORDRE`) VALUES (NULL, 'Etablissements Prévision', '6', '3');


-- une nouvelle demande : remplacement de AS par SH

-- demande de karine le 14/01/2021 ajout de type de plan
INSERT INTO `typeplan` (`ID_TYPEPLAN`, `LIBELLE_TYPEPLAN`) VALUES (NULL, 'ORSEC'); 
INSERT INTO `typeplan` (`ID_TYPEPLAN`, `LIBELLE_TYPEPLAN`) VALUES (NULL, 'PPRT'); 
INSERT INTO `typeplan` (`ID_TYPEPLAN`, `LIBELLE_TYPEPLAN`) VALUES (NULL, 'PSI'); 
INSERT INTO `typeplan` (`ID_TYPEPLAN`, `LIBELLE_TYPEPLAN`) VALUES (NULL, 'PPP'); 
INSERT INTO `typeplan` (`ID_TYPEPLAN`, `LIBELLE_TYPEPLAN`) VALUES (NULL, 'PSS'); 
INSERT INTO `typeplan` (`ID_TYPEPLAN`, `LIBELLE_TYPEPLAN`) VALUES (NULL, 'PCS'); 
INSERT INTO `typeplan` (`ID_TYPEPLAN`, `LIBELLE_TYPEPLAN`) VALUES (NULL, 'PPE'); 
INSERT INTO `typeplan` (`ID_TYPEPLAN`, `LIBELLE_TYPEPLAN`) VALUES (NULL, 'PPRI'); 
INSERT INTO `typeplan` (`ID_TYPEPLAN`, `LIBELLE_TYPEPLAN`) VALUES (NULL, 'PPRN'); 
INSERT INTO `typeplan` (`ID_TYPEPLAN`, `LIBELLE_TYPEPLAN`) VALUES (NULL, 'PLU'); 
INSERT INTO `typeplan` (`ID_TYPEPLAN`, `LIBELLE_TYPEPLAN`) VALUES (NULL, 'PUI'); 
INSERT INTO `typeplan` (`ID_TYPEPLAN`, `LIBELLE_TYPEPLAN`) VALUES (NULL, 'PIS'); 




-- ATTENTION : les requetes suivantes sont executées dans la deusième mise en production (après la migration des données !!!!

--- suite à la reunion du 01/04/2021 : mettre la date du 01/04/2021 à la place des dates null  (2734 PJ ont été modifiée)
UPDATE `piecejointe` SET `DATE_PIECEJOINTE` = '2021-04-01' WHERE `DATE_PIECEJOINTE` is null 

--- correction demandée par pascal le 29/04/2021

UPDATE `fonction` SET `LIBELLE_FONCTION` = 'Contrôleur technique (organisme agréé)' WHERE `fonction`.`ID_FONCTION` = 6; 

-- demande de karine le 23/06/2021 par email : ajouter une date d'insertion au dossier 

SELECT * FROM `dossier` WHERE ID_DOSSIER <86547 AND ID_DOSSIER > 82673  

UPDATE `dossier` SET `DATEINSERT_DOSSIER` = '2021-04-01' WHERE ID_DOSSIER <86547 AND ID_DOSSIER > 82673

--- demande de Karine et Christophe (oublie des natures de quelques dossier 224) : ajout en en production de la nature ID_NATURE= 6 à chaque dossier

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82675');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82685');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82703');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82709');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82719');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82729');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82731');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82734');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82740');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82785');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82788');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82789');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82803');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82811');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82819');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82836');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82847');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82859');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82867');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82890');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82919');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82920');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82921');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82939');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82946');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '82998');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83004');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83006');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83020');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83051');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83054');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83057');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83067');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83069');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83074');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83107');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83109');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83137');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83145');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83150');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83154');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83189');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83198');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83223');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83237');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83263');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83269');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83283');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83289');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83297');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83366');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83378');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83396');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83411');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83414');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83438');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83451');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83453');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83463');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83498');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83500');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83503');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83512');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83518');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83519');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83527');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83530');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83552');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83554');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83555');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83560');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83561');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83564');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83566');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83580');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83604');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83606');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83629');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83640');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83651');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83654');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83674');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83682');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83699');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83712');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83731');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83733');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83766');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83781');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83785');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83787');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83789');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83833');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83834');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83843');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83866');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83895');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83965');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83974');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '83991');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84007');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84035');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84072');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84088');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84100');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84104');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84140');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84141');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84165');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84166');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84197');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84204');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84226');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84227');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84270');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84271');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84272');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84286');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84353');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84359');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84428');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84429');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84448');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84570');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84622');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84626');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84725');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84732');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84735');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84739');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84760');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84794');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84803');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84837');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84841');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84842');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84845');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84846');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84902');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84906');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84921');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84930');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '84957');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85009');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85010');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85079');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85101');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85160');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85163');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85177');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85190');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85213');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85223');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85231');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85288');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85291');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85310');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85340');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85343');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85378');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85409');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85414');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85415');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85439');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85527');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85543');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85550');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85556');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85566');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85587');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85588');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85592');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85608');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85630');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85631');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85633');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85666');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85677');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85678');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85692');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85735');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85742');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85744');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85769');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85803');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85810');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85813');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85824');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85870');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85881');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85895');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85913');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85926');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85927');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85928');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85929');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85930');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85934');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85949');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85967');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '85973');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86047');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86074');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86085');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86109');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86130');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86165');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86180');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86183');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86202');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86252');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86267');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86290');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86334');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86341');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86395');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86397');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86398');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86411');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86471');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86480');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86503');

INSERT INTO `dossiernature` (`ID_DOSSIERNATURE`, `ID_NATURE`, `ID_DOSSIER`)
VALUES (NULL, '6', '86516');

--------  -------------------------------------------