<!doctype html>
<html lang="fr" >

    <head>

        <?php echo $this->render("includes/header.phtml"); ?>

    </head>

    <body class='login' >

        <div class="wrapper">
        
            <div class="block">

                <?php
                    // added by george
                    if(strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE')) {
                        // This user is using IE2 - IE10.
                        echo '<h2 style="color: #f00; text-align: center;">Vous devez impérativement utiliser le navigateur Firefox pour cette application';
                    }
                ?>
                <h1 class='text-center'>
                    <img src='/images/logo_prevarisc_big.jpg' alt='Prevarisc' />
                </h1>
            
                <div class='well'>

                    <?php echo $this->render("includes/notifications.phtml"); ?>

                    <?php echo $this->layout()->content; ?>  

                </div>
                
                <?php echo $this->render("includes/footer.phtml"); ?>
                
            </div>
            
        </div>
        
	</body>
    
</html>